Algoritmo "SucessorFACCAT"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : sucessor
// Autor(a)    : Lavinia
// Data atual  : 27/09/2025
Var
   // Seção de Declarações das variáveis
   sucessor:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("digite um valor")
   leia(valor1)
   sucessor<- valor1 + 1

   escreval("O sucessor do primeiro valor é = ", sucessor)
Fimalgoritmo